### ISSUE TITLE
yes, I am an ignorant and disrespectful person and I am happy with this..

### ISSUE THREAD

**Issue by daniele-niero** [nyotis/MayaWrapDeformer#1]
...

**Comment by nyotis** [comment]
no

**Comment by daniele-niero** [comment]
Cool, maybe you should set this repo to private, so people don't lose time looking at something that has no code? you know... just to be nice with the other users ;)

**Comment by nyotis** [comment]
...
@daniele-niero pity you have _no ide_a what you are talking about.. please create yr own deformer you can still a great starting point in my repo

**Comment by daniele-niero** [comment]
Question: No Code?
Answer: No.

Git hub is a place where to share code. You are not sharing code.

Being a nice person is not required but it will help you better than being
a jerk, trust me.

**Comment by nyotis** [comment]
why are you rude and swear?

**Comment by nyotis** [comment]
@daniele-niero 
ignorant and disrespectful guys like u should be *banned* from places like here for life... 
u do not even know what good programming and sharing is.
please read a book on developing Maya plygins and look elsewhere for copying and pasting some source code.
