### ISSUE TITLE
Missing source

### ISSUE THREAD

**Issue by PavelCrow** [nyotis/MayaWrapDeformer#2]
Hello Nik!
I can't to build the plugin. As I see, missing at least PfWrapDeformer.h
Can you help me with it?
Thank you.

**Comment by nyotis** [comment]
yes @PavelCrow that was intentional. Most likely I cannot upload the complete source due to copyright issues, but keep in mind that although the idea is still relevant my deformer is becoming dated (2011) - see Wiki for Autodesk's Shrink deformer (2016)
